extern
crypto_scalarmult_curve25519_amd64_51_fe25519_square( reg rp : u64,  reg xp : u64)
{
     reg cf : bool;

     reg r0 : u64;
     reg r1 : u64;
     reg r2 : u64;
     reg r3 : u64;
     reg r4 : u64;
     reg squarer01 : u64;
     reg squarer11 : u64;
     reg squarer21 : u64;
     reg squarer31 : u64;
     reg squarer41 : u64;
     reg squarerax : u64;
     reg squarerdx : u64;
     reg squareredmask : u64;
     reg squaret : u64;

    squarerax = xp[0];
    squarerdx, squarerax = squarerax * xp[0];
    r0 = squarerax;
    squarer01 = squarerdx;
    squarerax = xp[0];
    squarerax <<= 1;
    squarerdx, squarerax = squarerax * xp[1];
    r1 = squarerax;
    squarer11 = squarerdx;
    squarerax = xp[0];
    squarerax <<= 1;
    squarerdx, squarerax = squarerax * xp[2];
    r2 = squarerax;
    squarer21 = squarerdx;
    squarerax = xp[0];
    squarerax <<= 1;
    squarerdx, squarerax = squarerax * xp[3];
    r3 = squarerax;
    squarer31 = squarerdx;
    squarerax = xp[0];
    squarerax <<= 1;
    squarerdx, squarerax = squarerax * xp[4];
    r4 = squarerax;
    squarer41 = squarerdx;
    squarerax = xp[1];
    squarerdx, squarerax = squarerax * xp[1];
    cf ? r2 += squarerax;
    squarer21 += squarerdx + cf;
    squarerax = xp[1];
    squarerax <<= 1;
    squarerdx, squarerax = squarerax * xp[2];
    cf ? r3 += squarerax;
    squarer31 += squarerdx + cf;
    squarerax = xp[1];
    squarerax <<= 1;
    squarerdx, squarerax = squarerax * xp[3];
    cf ? r4 += squarerax;
    squarer41 += squarerdx + cf;
    squarerax = xp[1];
    squarerax *= 38;
    squarerdx, squarerax = squarerax * xp[4];
    cf ? r0 += squarerax;
    squarer01 += squarerdx + cf;
    squarerax = xp[2];
    squarerdx, squarerax = squarerax * xp[2];
    cf ? r4 += squarerax;
    squarer41 += squarerdx + cf;
    squarerax = xp[2];
    squarerax *= 38;
    squarerdx, squarerax = squarerax * xp[3];
    cf ? r0 += squarerax;
    squarer01 += squarerdx + cf;
    squarerax = xp[2];
    squarerax *= 38;
    squarerdx, squarerax = squarerax * xp[4];
    cf ? r1 += squarerax;
    squarer11 += squarerdx + cf;
    squarerax = xp[3];
    squarerax *= 19;
    squarerdx, squarerax = squarerax * xp[3];
    cf ? r1 += squarerax;
    squarer11 += squarerdx + cf;
    squarerax = xp[3];
    squarerax *= 38;
    squarerdx, squarerax = squarerax * xp[4];
    cf ? r2 += squarerax;
    squarer21 += squarerdx + cf;
    squarerax = xp[4];
    squarerax *= 19;
    squarerdx, squarerax = squarerax * xp[4];
    cf ? r3 += squarerax;
    squarer31 += squarerdx + cf;
    squareredmask = *(uint64_t *) crypto_scalarmult_curve25519_amd64_51_REDMASK51; // handle me 
    squarer01 = rotate128(squarer01, r0, 13);
    r0 &= squareredmask;
    squarer11 = rotate128(squarer11, r1, 13);
    r1 &= squareredmask;
    r1 += squarer01;
    squarer21 = rotate128(squarer21, r2, 13);
    r2 &= squareredmask;
    r2 += squarer11;
    squarer31 = rotate128(squarer31, r3, 13);
    r3 &= squareredmask;
    r3 += squarer21;
    squarer41 = rotate128(squarer41, r4, 13);
    r4 &= squareredmask;
    r4 += squarer31;
    squarer41 = squarer41 * 19;
    r0 += squarer41;
    squaret = r0;
    squaret >>= 51;
    squaret += r1;
    r0 &= squareredmask;
    r1 = squaret;
    squaret >>= 51;
    squaret += r2;
    r1 &= squareredmask;
    r2 = squaret;
    squaret >>= 51;
    squaret += r3;
    r2 &= squareredmask;
    r3 = squaret;
    squaret >>= 51;
    squaret += r4;
    r3 &= squareredmask;
    r4 = squaret;
    squaret >>= 51;
    squaret *= 19;
    r0 += squaret;
    r4 &= squareredmask;
    rp[0] = r0;
    rp[1] = r1;
    rp[2] = r2;
    rp[3] = r3;
    rp[4] = r4;
    return;
}
